services:
  mongodb:
    image: mongo:latest
    container_name: alimanaka-mongodb-new
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_new:/data/db

  backend:
    build: ./backend
    container_name: alimanaka-backend-new
    ports:
      - "8005:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/alimanaka
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: alimanaka-frontend-new
    ports:
      - "8004:3000"
    environment:
      - REACT_APP_API_URL=https://alimanaka.chantilly-shaula.ts.net:8443/api
    depends_on:
      - backend

volumes:
  mongodb_data_new:
